//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collèges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collèges()
        {
            this.Professions_Lgn_Tarifs = new HashSet<Professions_Lgn_Tarifs>();
        }
    
        public int Code_Collège { get; set; }
        public string Collège { get; set; }
        public string Libéllé_Complément { get; set; }
        public bool Formulaire { get; set; }
        public string Famille_collège { get; set; }
        public Nullable<bool> DADS { get; set; }
        public Nullable<int> ID_Famille_College { get; set; }
        public Nullable<int> ID_Statut_College { get; set; }
        public Nullable<int> Sagil_Cod_College { get; set; }
        public bool Actif { get; set; }
        public bool Sagil_Migre { get; set; }
        public Nullable<int> Sagil_Migre_Motif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professions_Lgn_Tarifs> Professions_Lgn_Tarifs { get; set; }
    }
}
