//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professions()
        {
            this.Professions_Lgn_Tarifs = new HashSet<Professions_Lgn_Tarifs>();
        }
    
        public int IdProf { get; set; }
        public string Profession { get; set; }
        public System.DateTime Debut_Prof { get; set; }
        public Nullable<System.DateTime> Fin_Prof { get; set; }
        public string Prof_Jazz { get; set; }
        public string Bareme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professions_Lgn_Tarifs> Professions_Lgn_Tarifs { get; set; }
    }
}
