//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version_Gar_Tarif
    {
        public int No_Version_Gar_Tarif { get; set; }
        public int No_Version_Gar { get; set; }
        public Nullable<System.DateTime> Dt_Effet_Tarif { get; set; }
        public Nullable<System.DateTime> Dt_Fin_Tarif { get; set; }
        public string Type_Cotis { get; set; }
        public Nullable<int> No_Base { get; set; }
        public string Borne_Inf { get; set; }
        public string Borne_Sup { get; set; }
        public Nullable<double> Tx { get; set; }
    }
}
