//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version_Garanties_Prev
    {
        public int No_Version_Gar { get; set; }
        public Nullable<int> No_garantie { get; set; }
        public Nullable<int> No_Version { get; set; }
        public Nullable<System.DateTime> Dt_Effet { get; set; }
        public Nullable<System.DateTime> Dt_Fin { get; set; }
        public Nullable<int> Typ_Fin { get; set; }
        public string Libelle_commercial { get; set; }
        public string Type_Garantie { get; set; }
    }
}
